/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: packet.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "packet.pb-c.h"
void   rpc_service__packet_stream__init
                     (RpcService__PacketStream         *message)
{
  static const RpcService__PacketStream init_value = RPC_SERVICE__PACKET_STREAM__INIT;
  *message = init_value;
}
size_t rpc_service__packet_stream__get_packed_size
                     (const RpcService__PacketStream *message)
{
  assert(message->base.descriptor == &rpc_service__packet_stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_service__packet_stream__pack
                     (const RpcService__PacketStream *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc_service__packet_stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_service__packet_stream__pack_to_buffer
                     (const RpcService__PacketStream *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc_service__packet_stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcService__PacketStream *
       rpc_service__packet_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcService__PacketStream *)
     protobuf_c_message_unpack (&rpc_service__packet_stream__descriptor,
                                allocator, len, data);
}
void   rpc_service__packet_stream__free_unpacked
                     (RpcService__PacketStream *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc_service__packet_stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc_service__data_response__init
                     (RpcService__DataResponse         *message)
{
  static const RpcService__DataResponse init_value = RPC_SERVICE__DATA_RESPONSE__INIT;
  *message = init_value;
}
size_t rpc_service__data_response__get_packed_size
                     (const RpcService__DataResponse *message)
{
  assert(message->base.descriptor == &rpc_service__data_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc_service__data_response__pack
                     (const RpcService__DataResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc_service__data_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc_service__data_response__pack_to_buffer
                     (const RpcService__DataResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc_service__data_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RpcService__DataResponse *
       rpc_service__data_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RpcService__DataResponse *)
     protobuf_c_message_unpack (&rpc_service__data_response__descriptor,
                                allocator, len, data);
}
void   rpc_service__data_response__free_unpacked
                     (RpcService__DataResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc_service__data_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc_service__packet_stream__field_descriptors[9] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, tid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, direction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_alert",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, is_alert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "classType",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, classtype),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eMsg",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RpcService__PacketStream, emsg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_service__packet_stream__field_indices_by_name[] = {
  7,   /* field[7] = classType */
  0,   /* field[0] = data */
  4,   /* field[4] = direction */
  8,   /* field[8] = eMsg */
  5,   /* field[5] = is_alert */
  1,   /* field[1] = length */
  6,   /* field[6] = sid */
  3,   /* field[3] = tid */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange rpc_service__packet_stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor rpc_service__packet_stream__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpcService.PacketStream",
  "PacketStream",
  "RpcService__PacketStream",
  "RpcService",
  sizeof(RpcService__PacketStream),
  9,
  rpc_service__packet_stream__field_descriptors,
  rpc_service__packet_stream__field_indices_by_name,
  1,  rpc_service__packet_stream__number_ranges,
  (ProtobufCMessageInit) rpc_service__packet_stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc_service__data_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RpcService__DataResponse, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RpcService__DataResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc_service__data_response__field_indices_by_name[] = {
  1,   /* field[1] = message */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange rpc_service__data_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc_service__data_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RpcService.DataResponse",
  "DataResponse",
  "RpcService__DataResponse",
  "RpcService",
  sizeof(RpcService__DataResponse),
  2,
  rpc_service__data_response__field_descriptors,
  rpc_service__data_response__field_indices_by_name,
  1,  rpc_service__data_response__number_ranges,
  (ProtobufCMessageInit) rpc_service__data_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor rpc_service__rpc_service__method_descriptors[1] =
{
  { "Entrance", &rpc_service__packet_stream__descriptor, &rpc_service__data_response__descriptor },
};
const unsigned rpc_service__rpc_service__method_indices_by_name[] = {
  0         /* Entrance */
};
const ProtobufCServiceDescriptor rpc_service__rpc_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "RpcService.RpcService",
  "RpcService",
  "RpcService__RpcService",
  "RpcService",
  1,
  rpc_service__rpc_service__method_descriptors,
  rpc_service__rpc_service__method_indices_by_name
};
void rpc_service__rpc_service__entrance(ProtobufCService *service,
                                        const RpcService__PacketStream *input,
                                        RpcService__DataResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &rpc_service__rpc_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void rpc_service__rpc_service__init (RpcService__RpcService_Service *service,
                                     RpcService__RpcService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &rpc_service__rpc_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
